### ISSUE TITLE
Ducksboard::Box is overly restrictive

### ISSUE THREAD

**Issue by afn** [jhsu/ducksboard#12]
`Box#valid?` returns false if the number is not an integer, but the Ducksboard API will accept floating-point values (contrary to what [their documentation](http://dev.ducksboard.com/apidoc/slot-kinds/#boxes) says).

**Comment by jhsu** [comment]
@afn fixed it to just check for a numeric type, pushed a version bump too

**Comment by afn** [comment]
@jhsu Dude that was impressive.  Thanks for the lightning-fast turnaround! :)

**Comment by jhsu** [comment]
thanks for reporting!
