### ISSUE TITLE
Bump gem version and push Leaderboard code to Rubygems

### ISSUE THREAD

**Issue by gabceb** [jhsu/ducksboard#5]
It seems that the last uploaded gem on Rubygem does not include the Leaderboard code changes. You guys should push the new code and bump the version.

**Comment by jhsu** [comment]
Bumped the version and pushed it (0.1.4) to rubygems. I'm not really sure what state this is in at the moment.

Unfortunately I haven't had time to pay much attention to this gem and keep up with ducksboard's API, as I don't use ducksboard daily. I had planned to refactor the code (1.0-refactor branch), but barely started it.

**Comment by gabceb** [comment]
Well that was a bad idea. Haha. Push is completely messed up now. I will try to submit a fix for it and could give you a hand refactoring everything

**Comment by jhsu** [comment]
yikes, yeah, any help with this would be great =)
